name: Update Target List

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 실행
  workflow_dispatch: # 수동 실행 버튼

jobs:
  update_targets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Target Extractor
        run: python find_targets.py
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}

      - name: Commit and Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "TargetBot"
          git add targets.json
          git commit -m "Update targets.json" || exit 0
          git push
